version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.3.3
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            sudo apt update
            sudo apt install -y nodejs npm
      - run:
          name: Set up npm global path
          command: |
            mkdir -p $HOME/.npm-global
            npm config set prefix $HOME/.npm-global
            export PATH=$HOME/.npm-global/bin:$PATH
            echo 'export PATH=$HOME/.npm-global/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Yarn
          command: |
            npm install -g yarn
      - run:
          name: Install dependencies
          command: |
            bundle install
            yarn install
      - run:
          name: Precompile Assets
          command: |
            bundle exec rails webpacker:compile
            bundle exec rake assets:precompile
      - run:
          name: Run Tests
          command: bundle exec rspec

  deploy:
    docker:
      - image: cimg/ruby:3.3.3
    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Authenticate with Heroku
          command: echo $HEROKU_API_KEY | heroku auth:token
      - run:
          name: Deploy to Heroku
          command: git push heroku main

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
