version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install -y nodejs npm
            node -v
      - run:
          name: Install rbenv & Ruby
          command: |
            sudo apt install -y rbenv
            export PATH="$HOME/.rbenv/bin:$PATH"
            eval "$(rbenv init -)"
            rbenv install 3.3.3
            rbenv global 3.3.3
            ruby -v
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Run Tests
          command: bundle exec rspec
      - run:
          name: Clear Cache
          command: rm -rf ~/.cache/yarn ~/.bundle

  deploy:
      machine: true
      steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Deploy to Heroku
          command: git push heroku main

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
