version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install -y nodejs npm
            node -v
      - run:
          name: Install Ruby & Bundler
          command: |
            sudo apt install -y ruby-full
            gem install bundler
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Run Tests
          command: bundle exec rspec
      - run:
          name: Clear Cache
          command: rm -rf ~/.cache/yarn ~/.bundle

  deploy:
      machine: true
      image: ubuntu-22.04
    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Deploy to Heroku
          command: git push heroku main

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test  
